### ISSUE TITLE
Sky with "thunder" weather condition pops in instantly

### ISSUE THREAD

**Issue by UsernameGeri** [AMereBagatelle/fabricskyboxes#76]
If you have a sky layer that's set to show during thunder, it won't fade in gradually, rather it will instantly pop in when the weather has fully transitioned to thunder. Using commands to set the weather, you can see how it takes a couple of seconds while the weather is changing, and then the sky pops in. Then if you set to rain weather, the thunder sky will instantly disappear.

https://user-images.githubusercontent.com/96586974/216759243-d192e8b0-7ee3-4c24-83e6-b27977bbe590.mp4

**Comment by FlashyReese** [comment]
Upon thorough investigation, it has been determined that the issue at hand is not related to the fade system but rather to the multiply blend. The alpha channel does not seem to be functioning correctly, despite the code suggesting otherwise. Further investigation is needed to determine the root cause of this issue.
