### ISSUE TITLE
Skybox render optimization

### ISSUE THREAD

**Issue by Mercenarioo** [AMereBagatelle/fabricskyboxes#91]
Hi, is it possible to optimize skybox rendering a bit?
![image](https://github.com/AMereBagatelle/fabricskyboxes/assets/107449914/4ea2963e-fdf2-4206-adb3-6e29c9641b0a)

**Comment by FlashyReese** [comment]
Can you post the entire profile link, I'm not sure how 1 would optimize multiple layers of skybox rendering

**Comment by Mercenarioo** [comment]
![image](https://github.com/AMereBagatelle/fabricskyboxes/assets/107449914/8979519b-6a37-4e5e-b4dd-2260ca89361a)

**Comment by FlashyReese** [comment]
Yeah, doesn't look like there is much I can personally do. I don't really know how to optimize Minecraft's rendering aspect. The hot code is just rendering the skybox textures and it gets worse if you have tons of active skyboxes.

**Comment by Mercenarioo** [comment]
Maybe you can ask some specialists like https://github.com/CaffeineMC/sodium-fabric or https://github.com/RaphiMC/ImmediatelyFast

**Comment by FlashyReese** [comment]
FSB prioritizes delivering a feature-rich custom skybox experience. While we aim for efficient code, optimizing Minecraft's rendering pipeline is not our expertise. The hot code issue falls outside our mod's focus, especially since this is code that Minecraft uses to render skies. We appreciate your understanding.
